name: Update IPs

on:
  schedule:
    - cron: "0 17 * * *"  # Runs every day at 00:00 GMT+7 (WIB)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run scripts to update IPs
        run: |
          python scripts/generate-github-ip.py
          python scripts/generate-uptimerobot-ip.py
          python scripts/generate-cloudflare-ip.py

      - name: Commit and Push Changes
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # stage any file changes to be committed
          git add .

          # make commit with staged changes
          git commit -m "Updated on $(TZ='Asia/Jakarta' date +'%Y-%m-%d %H:%M:%S')"

          # push the commit back up to source GitHub repository
          git push
